### ISSUE TITLE
The value of the -L argument is removed

### ISSUE THREAD

**Issue by Lucidiot** [Blacksmoke16/oq#103]
The `-L` argument, used to add directories to jq's module search path, seems to be missing its value when it gets sent to jq:

```bash
λ echo '{}' | oq -L this/folder/does/not/exist .
{}

λ echo '{}' | oq -L /tmp .     
-L takes a parameter: (e.g. -L /search/path or -L/search/path)
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```

Note that both `-L blah` and `-Lblah` are accepted according to the manpage.

**Comment by Blacksmoke16** [comment]
Can confirm this is a bug with accepting `-L` option with a space. Works fine w/o a space. E.g. `-Lmodules`.
