### ISSUE TITLE
Clarify mapping of arrays to XML

### ISSUE THREAD

**Issue by nichtich** [Blacksmoke16/oq#17]
Raised at <https://github.com/Blacksmoke16/oq/issues/16#issuecomment-512619976> there are some edge cases when mapping JSON with arrays to XML. In the end the handling is arbitrary convention but it should be consistent. Some examples:

~~~
$ echo '[]' | oq -o xml .
<root/>
~~~

*makes sense*

~~~
$ echo '["x",{}]' | oq -o xml .
<root><item>x</item><item/></root>
~~~

*this surprised me. Why support arrays on the root level at all?*

~~~
$ echo '{"a":[],"b":{},"c":null}' | oq -o xml . 
<root><b/><c/></root>
~~~

*why no `<a/>`?*

~~~
$ echo '{"a":[[]]}' | oq -o xml .
<root><a/></root>
~~~

*wtf?*

~~~
$ echo '{"x":[1,[2,[3]]]}' | oq . -o xml
<root>
  <x>1</x>
  <x>
    <item>2</item>
    <item>
      <item>3</item>
    </item>
  </x>
</root>
~~~

*Ok, there is some logic here*

**Comment by Blacksmoke16** [comment]
The third case there is probably since the array is empty, so it doesn't add any elements.  Would just want to emit an empty tag in that case.  Which would make sense why the fourth has the empty tag since it has an element.

Nested array stuff like this should get better in my refactor.

**Comment by Blacksmoke16** [comment]
Boy, what a PITA.  This is what I got working currently.  Probably going to call it good enough.

```xml
echo '[]' | ./bin/oq -o xml .
<?xml version="1.0" encoding="UTF-8"?>
<root/>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <item>x</item>
  <item/>
</root>
```
Just because it's prob easier than not allowing it.  Maybe useful concating a bunch of stuff together? idk.

```xml
echo '{"a":[],"b":{},"c":null}' | ./bin/oq -o xml .
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <a/>
  <b/>
  <c/>
</root>
```

```xml
echo '{"a":[[]]}' | ./bin/oq -o xml .
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <a>
    <item/>
  </a>
</root>
```

```xml
echo '{"x":[1,[2,[3]]]}' | ./bin/oq . -o xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <x>1</x>
  <x>
    <item>2</item>
    <item>
      <item>3</item>
    </item>
  </x>
</root>
```

```xml
echo '{"x":[1,2,3]}' | ./bin/oq . -o xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <x>1</x>
  <x>
    <item>2</item>
    <item>
      <item>3</item>
    </item>
  </x>
</root>
```

```xml
echo '{"x":[1,2,3]}' | ./bin/oq . -o xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <x>1</x>
  <x>2</x>
  <x>3</x>
</root>
```

I'm probably going to call this sufficient
