### ISSUE TITLE
Cuts off after so much data

### ISSUE THREAD

**Issue by absolutejam** [Blacksmoke16/oq#29]
Morning!

I'm trying to cat https://docs.docker.com/engine/api/v1.30/swagger.yaml into oq with the following:
```
cat swagger.yaml | oq -f yaml
```

But I've noticed the output is truncated, and the point in which this happens is different every time.

Is the a limit on the amount of data accepted?

**Comment by Blacksmoke16** [comment]
@absolutejam I'm more surprised that command is working for you.  

```
cat swagger.yaml | oq -f yaml
jq: Could not open yaml: No such file or directory
```

The proper command should be

`cat swagger.yaml | oq -i yaml .`

Let me know if that fixes it.

**Comment by Blacksmoke16** [comment]
Was also able to do `cat swagger.yaml | oq -i yaml . | pbcopy` and paste the output into sublime and it was all there.  So deff seems to be just a terminal issue.  Piping the output to `less` also shows everything.

Feel free to reopen if you discover some new info that would suggest its an `oq` issue.

**Comment by dscottboggs** [comment]
It doesn't seem that hard to me to have a global constant like

```crystal
LESS_PROC = Process.new("less", input: Process::Redirect::PIPE, output: Process::Redirect::INHERIT, error: Process::Redirect::INHERIT)
OUTPUT = if STDOUT.tty?
  LESS_PROC.input
else
  STDOUT
end
```

Granted, if you don't think it's desirable to have the output in a pager by default, that's valid, but I don't think it's too big of a deal to implement.

**Comment by Blacksmoke16** [comment]
Yea, I think I'd rather keep it up to the user and not make any assumptions on how they want the data outputted.

**Comment by jmagnusson** [comment]
Cuts off in the middle for me as well using command `curl https://docs.docker.com/engine/api/v1.30/swagger.yaml | oq -i yaml .`

On macOS 10.14.6. Installed today via brew.

**Comment by Blacksmoke16** [comment]
Yea @jmagnusson.  We already determined this is isn't specifically an `oq` issue, just how your shell handles the output.  As I mentioned in https://github.com/Blacksmoke16/oq/issues/29#issuecomment-520191201 you could pipe to `less` or a file.

**Comment by jmagnusson** [comment]
Hmm are you sure?

I just built `oq` from source. Tags v0.2.1, v0.2.0 give the same error. v0.1.1 gives the complete output.

**Comment by Blacksmoke16** [comment]
> v0.1.1 gives the complete output.

Oh interesting.  I'll reopen this and look into it some more in that case.

**Comment by Blacksmoke16** [comment]
@jmagnusson try out the `wait-for-fibers` branch.  Seems there was an issue where I think the program was exiting before the fiber that was doing the serialization was finished.

**Comment by jmagnusson** [comment]
@Blacksmoke16 no cut-offs with that branch 👍
