### ISSUE TITLE
Support XML as input format

### ISSUE THREAD

**Issue by Blacksmoke16** [Blacksmoke16/oq#31]
Let's support normal XML before starting on #7.  This will lay the groundwork for the logic required to parse the XML.  Altering the output JSON should then be easier.

**Comment by Blacksmoke16** [comment]
Hey @nichtich.  If you had an XML document like:

```xml
<root>
  <one>  </one>
  <two>
  </two>
</root>
```

Would you expect the output to be:
```json
{
  "root": {
    "one": "Some Data",
    "two": "A bunch of data"
  }
}
```

Or
```json
{
  "root": {
    "one": "  Some Data",
    "two": "A bunch of data\n  "
  }
}
```

I.e. should the extra whitespace in the elements be considered significant? Or should it just be stripped out?

**Comment by nichtich** [comment]
Following XML practice in this case (in text only elements) the whitespace is significant, so the second variant
