### ISSUE TITLE
Automatically build and release a binary to GitHub as part of CI pipeline

### ISSUE THREAD

**Issue by Nowaker** [Blacksmoke16/oq#33]
Manual build and release of binary is prone to human errors. Please build and upload the binary to GitHub release directly from the Travis job. Thanks!

**Comment by Blacksmoke16** [comment]
This'll be easier to do with https://github.com/crystal-lang/distribution-scripts/pull/29.  Can use the official Alpine image to build that static binary.

**Comment by Blacksmoke16** [comment]
@Nowaker This is done, https://github.com/Blacksmoke16/oq/runs/437474259?check_suite_focus=true.
