### ISSUE TITLE
parse error: Invalid numeric literal at line 1, column 5

### ISSUE THREAD

**Issue by Nowaker** [Blacksmoke16/oq#34]
```
~ # cat blah.yml
lang:
- en
- es
~ # ./oq-0.2.0-linux-x86_64 -r '.' blah.yml
parse error: Invalid numeric literal at line 1, column 5
```

Same thing executed on a JSON equivalent of blah.yml using jq:

```
~ # cat blah.json
{"lang": ["en", "es"]}
~ # jq -r '.' blah.json
{
  "lang": [
    "en",
    "es"
  ]
}
```

Note: I use oq 0.2.0 because no Linux binaries were available.

EDIT: Thanks for providing the binary for 0.2.1. Same problem there:
```
~ # ./oq-0.2.1-linux-x86_64 -r '.' blah.yml
parse error: Invalid numeric literal at line 1, column 5
```

**Comment by Blacksmoke16** [comment]
The default input format is JSON, you would want to do.

`./oq-0.2.1-linux-x86_64 -i yaml -r . blah.yml`

in order to set the input format as `YAML`, which yields:

```bash
 ./oq-0.2.1-linux-x86_64 -i yaml -r . data.yaml 
{
  "lang": [
    "en",
    "es"
  ]
}
```

**Comment by Nowaker** [comment]
Thanks! I'll modify README.md later to indicate that.
